"""``gaia pkg formalize`` — upgrade scaffold queue items to formal warrants.

Spec §5.2 / §12. The deterministic projector emits ``depends_on(...)``,
``candidate_relation(...)``, and ``note(...)`` *scaffolds* for every
ambiguous host source. Each scaffold also gets an item in
``.gaia/formalization_queue.jsonl`` listing the legal upgrade paths
(``depends_on → infer / derive``, ``candidate_relation → equal /
contradict / exclusive``, ``note → claim / observe``, ...).

This verb walks the queue and applies user-chosen upgrades, writing
the new formal records into ``gaia/formalization/<file>.py`` and
marking the queue item ``resolved``. Two modes:

* ``--interactive`` (default when stdout is a TTY): prompt for each
  open item — choose one of ``candidate_actions``, write the rationale,
  or skip.
* non-interactive (``--auto-accept <kind>``): apply the named
  upgrade to every open item whose ``current_action`` matches a
  rule. Used by CI and agent loops; the agent supplies pre-vetted
  ``--auto-accept depends_on:infer`` mappings.

The verb never deletes the scaffold record — every upgrade is
expressed as a ``materialize(scaffold, by=formal_record, rationale=...)``
call. That keeps the audit chain intact (source_map points at the
scaffold; the scaffold's ``materialize`` link points at the formal
warrant) and makes formalization fully reversible: drop the new file,
re-run compile, the scaffold reverts to its raw form.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import typer

from gaia.cli.commands.author._envelope import (
    EXIT_INPUT_SYNTAX,
    EXIT_OK,
    EXIT_PREWRITE_STRUCTURAL,
    EXIT_SYSTEM_IO,
    AuthorResult,
    Diagnostic,
    emit,
)
from gaia.engine.codegen import Ref, render_call_statement, render_module
from gaia.engine.layout import (
    EMBEDDED_GAIA_DIR,
    EMBEDDED_GAIA_OUTPUT_DIR,
    GaiaLayoutError,
    LayoutKind,
    detect_layout,
)

_KNOWN_UPGRADES: dict[str, set[str]] = {
    "depends_on": {"infer", "derive"},
    "candidate_relation": {"equal", "contradict", "exclusive"},
    "note": {"claim", "observe"},
}

_FORMALIZATION_DIR = "formalization"
_FORMALIZATION_INIT = (
    '"""User- or agent-authored formalization upgrades over scaffold records.\n\n'
    "Generated by `gaia pkg formalize`. Each upgrade writes a new\n"
    "`materialize(scaffold, by=...)` call into a file under this folder.\n"
    "Delete the file (and rewind the matching `.gaia/formalization_queue.jsonl`\n"
    'entry to `status="open"`) to revert.\n"""\n\n'
    "__all__: list[str] = []\n"
)


@dataclass
class _AutoAcceptRule:
    """Parsed ``current_action[:chosen_action]`` pair from --auto-accept."""

    current_action: str
    chosen_action: str | None = None


@dataclass
class _Resolution:
    queue_id: str
    chosen_action: str
    rationale: str
    new_label: str
    scaffold_label: str
    by_label: str | None  # None when we synthesise a new record instead


@dataclass
class _FormalizeOutcome:
    resolved: list[_Resolution] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def _parse_auto_accept(rules: list[str]) -> list[_AutoAcceptRule]:
    parsed: list[_AutoAcceptRule] = []
    for raw in rules:
        if not raw:
            continue
        if ":" in raw:
            current, chosen = raw.split(":", 1)
            parsed.append(_AutoAcceptRule(current.strip(), chosen.strip()))
        else:
            parsed.append(_AutoAcceptRule(raw.strip()))
    return parsed


def _read_queue(queue_path: Path) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    if not queue_path.exists():
        return items
    for line in queue_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(entry, dict):
            items.append(entry)
    return items


def _write_queue(queue_path: Path, items: list[dict[str, Any]]) -> None:
    queue_path.write_text(
        "".join(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n" for item in items)
    )


def _read_source_map(map_path: Path) -> dict[str, Any]:
    if not map_path.exists():
        return {"records": []}
    try:
        data = json.loads(map_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"records": []}
    return data if isinstance(data, dict) else {"records": []}


def _write_source_map(map_path: Path, data: dict[str, Any]) -> None:
    map_path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def _pick_for_item(
    item: dict[str, Any],
    *,
    auto_accept: list[_AutoAcceptRule],
    interactive: bool,
) -> tuple[str | None, str]:
    """Return ``(chosen_action, rationale)`` or ``(None, reason)`` to skip.

    Auto-accept wins over interactive prompting so an agent can drive
    non-interactive runs even on a TTY.
    """
    current = str(item.get("current_action") or "")
    candidates = list(item.get("candidate_actions") or [])
    valid = set(candidates) & _KNOWN_UPGRADES.get(current, set(candidates))
    for rule in auto_accept:
        if rule.current_action != current:
            continue
        chosen = rule.chosen_action
        if chosen is None:
            if len(valid) == 1:
                return next(iter(valid)), "Auto-accepted single available candidate."
            continue
        if chosen in valid:
            return chosen, f"Auto-accepted '{chosen}' for current_action='{current}'."
    if not interactive:
        return None, "No matching --auto-accept rule and not interactive."
    return _prompt(item, valid)


def _prompt(item: dict[str, Any], valid: set[str]) -> tuple[str | None, str]:
    queue_id = item.get("queue_id", "?")
    source_id = item.get("source_id", "?")
    reason = item.get("reason_review_needed", "")
    typer.echo(f"\n[{queue_id}] {source_id}")
    typer.echo(f"  reason: {reason}")
    typer.echo(f"  candidates: {', '.join(sorted(valid)) or '(none)'}")
    typer.echo("  type the candidate name to apply, or empty to skip:")
    try:
        chosen = typer.prompt("  choice", default="", show_default=False)
    except typer.Abort:  # pragma: no cover — Ctrl-C during prompt
        return None, "Aborted by user."
    chosen = chosen.strip()
    if not chosen:
        return None, "Skipped by user."
    if chosen not in valid:
        return None, f"Invalid choice {chosen!r}; allowed: {sorted(valid)}."
    rationale = typer.prompt("  rationale", default="")
    return chosen, rationale.strip() or "Resolved through `gaia pkg formalize`."


def _safe_label(prefix: str, raw: str) -> str:
    safe = re.sub(r"[^a-z0-9_]+", "_", raw.lower()).strip("_") or "x"
    return f"{prefix}_{safe}"


def _render_formalization_module(
    resolutions: list[_Resolution],
    *,
    extra_imports: tuple[str, ...] = (),
) -> str:
    """Build the source for ``gaia/formalization/<batch>.py``.

    Each resolution emits two statements:

    1. A formal warrant call (``infer(...)`` / ``derive(...)`` /
       ``contradict(...)`` / etc) parameterised against the original
       scaffold's referenced records. Defaults are intentionally weak
       — no probabilities, generic rationale — because the projector
       does not know enough to commit numbers; reviewers can tighten
       later.
    2. A ``materialize(scaffold, by=warrant, rationale=...)`` call
       linking the scaffold to the new warrant so the source_map
       audit chain stays connected.

    *extra_imports* is a tuple of explicit ``from .. import ...`` lines
    the renderer should preserve verbatim (e.g. for the scaffold
    labels this batch references — they live in sibling packages and
    must be imported explicitly).
    """
    if not resolutions:
        return ""
    statements: list[str] = []
    labels: list[str] = []
    engine_imports: set[str] = {"materialize"}
    for resolution in resolutions:
        warrant_label = resolution.new_label
        labels.append(warrant_label)
        engine_imports.add(resolution.chosen_action)
        statements.append(_render_warrant_statement(resolution, warrant_label))
        link_label = f"{warrant_label}_materializes"
        labels.append(link_label)
        # Pass the warrant's label *as a string* rather than its
        # in-process Claim reference so ``materialize`` can resolve
        # the warrant unambiguously even when the engine internally
        # registers multiple graph records for the same call (a
        # ``derive`` produces both a Claim and a Strategy; without
        # the label lookup the resolution is "ambiguous").
        statements.append(
            render_call_statement(
                target_label=link_label,
                func_name="materialize",
                positional=[Ref(resolution.scaffold_label)],
                keywords={
                    "by": warrant_label,
                    "rationale": resolution.rationale,
                    "metadata": {
                        "queue_id": resolution.queue_id,
                        "upgraded_from": "scaffold",
                    },
                },
            )
        )
    return render_module(
        docstring=(
            "Formalization upgrades produced by `gaia pkg formalize`.\n\n"
            "Each scaffold record is paired with a formal warrant and a "
            "`materialize(...)` link. Removing the file (and resetting the "
            'matching queue entry to `status="open"`) reverts the upgrade.'
        ),
        engine_imports=tuple(sorted(engine_imports)),
        extra_imports=extra_imports,
        statements=statements,
        all_labels=labels,
    )


def _resolve_scaffold_imports(
    resolutions: list[_Resolution],
    source_map_records: list[dict[str, Any]],
) -> tuple[str, ...]:
    """Build ``from ..<pkg>.<module> import <labels>`` lines for each scaffold.

    The formalization module references scaffold labels (``ara_c01_depends_on_e01``)
    and possibly the scaffold's "hypothesis" sibling (``ara_c01``). Both live
    in modules under ``gaia/from_ara/`` (or ``from_arm/``, ``from_host/``),
    not in ``gaia/formalization/``. We need an explicit import line per source
    module so the warrant + materialize statements resolve at load time.
    """
    # Map gaia_label → relative-import path inside the gaia/ folder.
    label_to_module: dict[str, str] = {}
    for record in source_map_records:
        generated_file = record.get("generated_file")
        label = record.get("gaia_label")
        if not isinstance(generated_file, str) or not isinstance(label, str):
            continue
        if not generated_file.startswith("gaia/"):
            continue
        rel_module = generated_file.removeprefix("gaia/").removesuffix(".py")
        if not rel_module:
            continue
        # rel_module is dotted form like "from_ara.claims" or "from_host/notes"
        dotted = rel_module.replace("/", ".")
        label_to_module[label] = dotted

    needed: dict[str, set[str]] = {}
    for resolution in resolutions:
        for ref_label in (
            resolution.scaffold_label,
            _scaffold_hypothesis_label(resolution),
            _scaffold_premise_label(resolution),
            resolution.by_label,
        ):
            if not ref_label:
                continue
            module = label_to_module.get(ref_label)
            if module is None:
                continue
            needed.setdefault(module, set()).add(ref_label)

    imports: list[str] = []
    for module in sorted(needed):
        names = ", ".join(sorted(needed[module]))
        imports.append(f"from ..{module} import {names}")
    return tuple(imports)


def _render_warrant_statement(resolution: _Resolution, warrant_label: str) -> str:
    """Render one formal-warrant call from a resolution.

    The projector does not know the user's chosen likelihoods or
    explicit premise lists; we emit a conservative default (a
    `note(...)`-shaped placeholder when in doubt) and rely on the
    user/agent editing the file afterwards to plug numbers in.
    """
    if resolution.chosen_action == "infer":
        # Spec §7.2 example: ``infer(evidence, hypothesis=..., p_e_given_h=...,
        # p_e_given_not_h=...)``. The numeric likelihoods are NOT
        # programmatic defaults — they require reviewer acceptance.
        # We emit conservative placeholders (0.5 / 0.5 = "the evidence
        # does not move belief either way") and tag them in the
        # rationale so the reviewer sees what to replace. The explicit
        # ``label=`` lets ``materialize(by="<label>")`` look the
        # warrant up unambiguously regardless of how many graph records
        # the engine registers internally.
        evidence_label = _scaffold_premise_label(resolution)
        hypothesis_label = _scaffold_hypothesis_label(resolution)
        rationale = (
            f"{resolution.rationale} TODO(reviewer): replace placeholder "
            "p_e_given_h=0.5, p_e_given_not_h=0.5 with vetted likelihoods."
        )
        return render_call_statement(
            target_label=warrant_label,
            func_name="infer",
            positional=[Ref(evidence_label)],
            keywords={
                "hypothesis": Ref(hypothesis_label),
                "p_e_given_h": 0.5,
                "p_e_given_not_h": 0.5,
                "rationale": rationale,
                "label": warrant_label,
            },
        )
    if resolution.chosen_action == "derive":
        return render_call_statement(
            target_label=warrant_label,
            func_name="derive",
            positional=[
                "Deterministic derivation upgraded from a scaffold; "
                "fill in the actual derivation text."
            ],
            keywords={
                "given": [Ref(resolution.by_label or resolution.scaffold_label)],
                "rationale": resolution.rationale,
                "label": warrant_label,
            },
        )
    if resolution.chosen_action in {"contradict", "equal", "exclusive"}:
        return render_call_statement(
            target_label=warrant_label,
            func_name=resolution.chosen_action,
            positional=[
                Ref(resolution.by_label or resolution.scaffold_label),
                Ref(_scaffold_hypothesis_label(resolution)),
            ],
            keywords={"rationale": resolution.rationale, "label": warrant_label},
        )
    if resolution.chosen_action == "claim":
        return render_call_statement(
            target_label=warrant_label,
            func_name="claim",
            positional=[
                "Promoted claim from scaffold note; rewrite the body to match the actual assertion."
            ],
            keywords={"rationale": resolution.rationale} if resolution.rationale else {},
        )
    if resolution.chosen_action == "observe":
        return render_call_statement(
            target_label=warrant_label,
            func_name="observe",
            positional=["Promoted observation from scaffold note."],
            keywords={"rationale": resolution.rationale} if resolution.rationale else {},
        )
    # Default: bare note() — defensive fall-through, should not happen
    # because _pick_for_item only returns chosen_action in _KNOWN_UPGRADES.
    return render_call_statement(
        target_label=warrant_label,
        func_name="note",
        positional=[f"Unhandled upgrade target '{resolution.chosen_action}'."],
    )


def _scaffold_hypothesis_label(resolution: _Resolution) -> str:
    """Best-guess label of the *conclusion* side of a depends_on/candidate.

    depends_on labels generated by the ARA projector follow the
    convention ``<conclusion>_depends_on_<premise>`` (see
    ``projector/ara.py``); split on the literal infix to recover the
    conclusion label.
    """
    if "_depends_on_" in resolution.scaffold_label:
        return resolution.scaffold_label.split("_depends_on_", 1)[0]
    return resolution.scaffold_label


def _scaffold_premise_label(resolution: _Resolution) -> str:
    """Best-guess label of the *premise* (evidence) side of a depends_on scaffold."""
    if "_depends_on_" in resolution.scaffold_label:
        suffix = resolution.scaffold_label.split("_depends_on_", 1)[1]
        # The premise is labelled ``ara_evidence_<eid>`` in the
        # projector; reconstruct that prefix.
        return f"ara_evidence_{suffix}"
    return resolution.by_label or resolution.scaffold_label


def _by_label_from_record(record: dict[str, Any]) -> str | None:
    """Return the scaffold's primary premise label, if recoverable from source_map.

    Today's source_map shape does not carry premise references for
    scaffold records, so this is a stub returning ``None``; the
    warrant renderer reconstructs the premise from the ARA-projector
    label convention via :func:`_scaffold_premise_label`. Keeping the
    function gives a single edit point if a future source_map
    revision starts carrying premise lists explicitly.
    """
    del record
    return None


def _formalize_impl(
    *,
    host: Path,
    auto_accept: list[_AutoAcceptRule],
    interactive: bool,
    batch_name: str,
) -> _FormalizeOutcome:
    out_dir = host / EMBEDDED_GAIA_OUTPUT_DIR
    queue_path = out_dir / "formalization_queue.jsonl"
    map_path = out_dir / "source_map.json"
    items = _read_queue(queue_path)
    source_map = _read_source_map(map_path)
    source_map_records = source_map.get("records") or []
    record_by_id: dict[str, dict[str, Any]] = {
        str(r.get("source_id")): r for r in source_map_records if isinstance(r, dict)
    }

    outcome = _FormalizeOutcome()
    for item in items:
        if item.get("status") != "open":
            continue
        chosen, rationale_or_reason = _pick_for_item(
            item, auto_accept=auto_accept, interactive=interactive
        )
        if chosen is None:
            outcome.skipped.append(f"{item.get('queue_id')}: {rationale_or_reason}")
            continue
        record = record_by_id.get(str(item.get("source_id"))) or {}
        scaffold_label = str(item.get("current_gaia_record") or record.get("gaia_label") or "x")
        new_label = _safe_label(f"f_{chosen}", scaffold_label)
        resolution = _Resolution(
            queue_id=str(item.get("queue_id") or ""),
            chosen_action=chosen,
            rationale=rationale_or_reason or "Resolved through `gaia pkg formalize`.",
            new_label=new_label,
            scaffold_label=scaffold_label,
            by_label=_by_label_from_record(record),
        )
        outcome.resolved.append(resolution)
        # Mutate the queue item in place to record the resolution.
        item["status"] = "resolved"
        item["chosen_action"] = chosen
        item["chosen_label"] = new_label
        item["rationale"] = resolution.rationale
        item["provenance"] = (
            "user-confirmed" if interactive and not auto_accept else "auto-accepted"
        )

    if not outcome.resolved:
        return outcome

    # Write the new formalization module.
    formalization_dir = host / EMBEDDED_GAIA_DIR / _FORMALIZATION_DIR
    formalization_dir.mkdir(parents=True, exist_ok=True)
    init_path = formalization_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(_FORMALIZATION_INIT)
    module_path = formalization_dir / f"{batch_name}.py"
    extra_imports = _resolve_scaffold_imports(outcome.resolved, source_map_records)
    module_path.write_text(
        _render_formalization_module(outcome.resolved, extra_imports=extra_imports)
    )

    # Also re-export from the embedded root so the loader picks the new labels up.
    root_init = host / EMBEDDED_GAIA_DIR / "__init__.py"
    if root_init.exists():
        body = root_init.read_text()
        snippet = f"\nfrom .{_FORMALIZATION_DIR}.{batch_name} import *  # noqa: F401,F403\n"
        if snippet.strip() not in body:
            root_init.write_text(body.rstrip() + "\n" + snippet)

    _write_queue(queue_path, items)

    # Append source_map records pointing at the new formalization module.
    for resolution in outcome.resolved:
        source_map_records.append(
            {
                "source_id": f"FORMALIZE:{resolution.queue_id}",
                "source_path": f"gaia/{_FORMALIZATION_DIR}/{batch_name}.py",
                "source_anchor": None,
                "gaia_label": resolution.new_label,
                "gaia_record_kind": resolution.chosen_action,
                "generated_file": f"gaia/{_FORMALIZATION_DIR}/{batch_name}.py",
                "projection_rule": "formalize.upgrade.v1",
                "confidence": "user" if interactive else "agent",
                "requires_review": False,
                "queue_id": resolution.queue_id,
                "supersedes": resolution.scaffold_label,
            }
        )
    source_map["records"] = source_map_records
    _write_source_map(map_path, source_map)
    return outcome


def formalize_command(
    host: str = typer.Argument(
        ".",
        help=(
            "Embedded Gaia host (the directory that contains "
            "`gaia/gaia.toml` + `.gaia/formalization_queue.jsonl`)."
        ),
    ),
    auto_accept: list[str] = typer.Option(  # noqa: B008
        [],
        "--auto-accept",
        help=(
            "Repeatable. Apply an upgrade non-interactively when "
            "`current_action[:chosen_action]` matches a queue item. "
            "Omit the chosen action to accept the queue's sole candidate."
        ),
    ),
    interactive: bool = typer.Option(
        sys.stdin.isatty(),
        "--interactive/--no-interactive",
        help=(
            "Prompt for each open queue item. Defaults to TTY mode; "
            "disable in CI / agent loops in favour of `--auto-accept`."
        ),
    ),
    batch_name: str = typer.Option(
        "batch001",
        "--batch-name",
        help="File stem for the generated `gaia/formalization/<batch>.py` module.",
    ),
    human: bool = typer.Option(False, "--human", help="Human-readable envelope."),
    json_: bool = typer.Option(True, "--json/--no-json", help="JSON-first output (default)."),
) -> None:
    r"""Upgrade scaffold queue items to formal warrants.

    Examples:

    .. code-block:: bash

        # Interactive review of every open item.
        gaia pkg formalize ./my-host

        # Non-interactive: upgrade every depends_on → infer.
        gaia pkg formalize ./my-host --no-interactive \
            --auto-accept depends_on:infer

        # Non-interactive: pick the queue's sole candidate for each item.
        gaia pkg formalize ./my-host --no-interactive --auto-accept depends_on
    """
    del json_
    host_path = Path(host).resolve()
    try:
        layout = detect_layout(host_path)
    except GaiaLayoutError as exc:
        emit(
            AuthorResult(
                verb="formalize",
                status="error",
                code=EXIT_SYSTEM_IO,
                payload={"host": str(host_path)},
                diagnostics=[
                    Diagnostic(
                        kind="prewrite.target_invalid",
                        level="error",
                        message=str(exc),
                        source="prewrite",
                        where={"host": str(host_path)},
                    )
                ],
            ),
            human=human,
        )
        return
    if layout.kind is not LayoutKind.EMBEDDED:
        emit(
            AuthorResult(
                verb="formalize",
                status="error",
                code=EXIT_INPUT_SYNTAX,
                payload={"host": str(host_path), "layout": layout.kind.value},
                diagnostics=[
                    Diagnostic(
                        kind="prewrite.target_invalid",
                        level="error",
                        message=(
                            f"`gaia pkg formalize` only runs on embedded layouts; "
                            f"this host is {layout.kind.value!r}. Migrate first with "
                            "`gaia pkg migrate`."
                        ),
                        source="prewrite",
                        where={"host": str(host_path)},
                    )
                ],
            ),
            human=human,
        )
        return

    rules = _parse_auto_accept(auto_accept)
    try:
        outcome = _formalize_impl(
            host=host_path,
            auto_accept=rules,
            interactive=interactive,
            batch_name=batch_name,
        )
    except (OSError, PermissionError) as exc:
        emit(
            AuthorResult(
                verb="formalize",
                status="error",
                code=EXIT_SYSTEM_IO,
                payload={"host": str(host_path)},
                diagnostics=[
                    Diagnostic(
                        kind="prewrite.target_invalid",
                        level="error",
                        message=str(exc),
                        source="prewrite",
                        where={"host": str(host_path)},
                    )
                ],
            ),
            human=human,
        )
        return

    payload: dict[str, Any] = {
        "host": str(host_path),
        "resolved": [
            {
                "queue_id": r.queue_id,
                "chosen_action": r.chosen_action,
                "new_label": r.new_label,
                "scaffold_label": r.scaffold_label,
                "rationale": r.rationale,
            }
            for r in outcome.resolved
        ],
        "skipped": outcome.skipped,
        "batch_module": (
            f"gaia/{_FORMALIZATION_DIR}/{batch_name}.py" if outcome.resolved else None
        ),
    }
    code = EXIT_OK if outcome.resolved or not outcome.skipped else EXIT_PREWRITE_STRUCTURAL
    emit(
        AuthorResult(verb="formalize", status="ok", code=code, payload=payload),
        human=human,
    )


__all__ = ["formalize_command"]
