#!/usr/bin/env bash
#
# CLI-authored Galileo walkthrough (strict-reproducibility)
#
# Bundled with `gaia example galileo`. The placeholder
# './galileo-cli-mirror-gaia' is substituted by the cli verb when
# `--target NAME` is passed. Run the cli verb to print or save this
# script:
#
#     gaia example galileo
#     gaia example galileo --target ./my-demo
#     gaia example galileo --out walkthrough.sh
#
set -euo pipefail


# 1. Scaffold the package skeleton

gaia pkg scaffold \
    --target ./galileo-cli-mirror-gaia \
    --name galileo-v0-5-gaia \
    --namespace example

python -c "
import pathlib
p = pathlib.Path('galileo-cli-mirror-gaia/src/galileo_v0_5/__init__.py')
src = p.read_text()
end = src.find('hypothesis = claim(')
if end > 0:
    p.write_text(src[:end].rstrip() + '\n')
"


# 2. Author the three contextual notes

gaia author note \
  "This package models Galileo's falling-body thought experiment as a comparison between two explanatory models. It does not treat vacuum falling as an observed fact inside the package." \
  --label context \
  --target ./galileo-cli-mirror-gaia

gaia author note \
  "In the tied-body thought experiment, a heavy body and a light body are bound together and considered as one composite system." \
  --label thought_experiment_setup \
  --target ./galileo-cli-mirror-gaia

gaia author note \
  "The vacuum case is a counterfactual setup in which the resisting medium is absent." \
  --label vacuum_setup \
  --target ./galileo-cli-mirror-gaia


# 3. Author the model + observation claims

gaia author claim \
  "In air, heavy bodies are often observed to fall faster than light bodies." \
  --label daily_observation \
  --target ./galileo-cli-mirror-gaia

gaia author claim \
  "Model A: weight itself causes heavier bodies to have greater natural falling speed." \
  --label aristotle_model \
  --target ./galileo-cli-mirror-gaia

gaia author claim \
  "Model B: differences in falling speed in air are caused by resistance from the medium." \
  --label medium_model \
  --target ./galileo-cli-mirror-gaia


# 4. Author the daily-observation derivations + matches

gaia author derive \
  --conclusion-prose "Under Model A, heavy bodies should fall faster than light bodies in air." \
  --given aristotle_model \
  --rationale "If weight directly increases natural falling speed, then heavier bodies falling faster in air is expected." \
  --label aristotle_daily_observation_path \
  --target ./galileo-cli-mirror-gaia

gaia author equal \
  --a aristotle_daily_observation_path --b daily_observation \
  --rationale "The daily falling-body observation matches the prediction generated by the weight-speed model." \
  --label aristotle_daily_match \
  --target ./galileo-cli-mirror-gaia

gaia author derive \
  --conclusion-prose "Under Model B, heavy bodies can fall faster than light bodies in air." \
  --given medium_model \
  --rationale "If air resistance creates the observed speed differences, then heavier compact bodies can fall faster in air without weight itself setting the natural speed." \
  --label medium_daily_observation_path \
  --target ./galileo-cli-mirror-gaia

gaia author equal \
  --a medium_daily_observation_path --b daily_observation \
  --rationale "The daily falling-body observation matches the prediction generated by the medium-resistance model." \
  --label medium_daily_match \
  --target ./galileo-cli-mirror-gaia


# 5. Author the thought-experiment paradox under Model A

gaia author derive \
  --conclusion-prose "The tied composite should fall faster than the heavy body alone." \
  --given aristotle_model --background thought_experiment_setup \
  --rationale "Under the weight-speed model, greater total weight implies greater natural falling speed. In the tied-body setup, the composite contains the heavy body plus an additional light body, so it is heavier than the heavy body alone." \
  --label aristotle_composite_faster \
  --target ./galileo-cli-mirror-gaia

gaia author derive \
  --conclusion-prose "The tied composite should fall slower than the heavy body alone." \
  --given aristotle_model --background thought_experiment_setup \
  --rationale "Under the same weight-speed model, the slower light body should retard the faster heavy body when the two are tied together." \
  --label aristotle_composite_slower \
  --target ./galileo-cli-mirror-gaia

gaia author contradict \
  --a aristotle_composite_faster --b aristotle_composite_slower \
  --rationale "For the same tied composite, the weight-speed model yields incompatible predictions." \
  --label aristotle_paradox \
  --target ./galileo-cli-mirror-gaia


# 6. Author the vacuum prediction under Model B

gaia author derive \
  --conclusion-prose "In vacuum, bodies of different weights fall at the same rate." \
  --given medium_model --background vacuum_setup \
  --rationale "If observed speed differences come from medium resistance, then in the vacuum setup, where the resisting medium is absent by definition, the source of those differences is absent." \
  --label medium_vacuum_equal_fall_prediction \
  --target ./galileo-cli-mirror-gaia


# 7. Register the empirical-background prior in `priors.py`

gaia pkg add-module \
  --name priors \
  --imports register_prior \
  --target ./galileo-cli-mirror-gaia

gaia author register-prior \
  --claim daily_observation \
  --value 0.90 \
  --justification "The everyday observation is treated as familiar empirical background, not as a new vacuum experiment." \
  --file priors.py \
  --target ./galileo-cli-mirror-gaia

cd galileo-cli-mirror-gaia
gaia build compile
# → Compiled 24 knowledge, 5 strategies, 3 operators
gaia build check
