"""Seed-only projector for hosts with no recognised structure.

Used when :func:`gaia.engine.projector.host_kind.detect_host_kind`
returns ``GENERIC`` or ``PYTHON_PACKAGE``. The rules are intentionally
trivial — for each ``--from <file>`` the user named, emit a
``note(...)`` stub in ``gaia/from_host/<safe_stem>.py``, record the
binding in source_map, and seed a formalization queue item.

This is the same surface the alpha ``gaia pkg mount --from`` shipped,
extracted here so the dispatcher in :mod:`api` has a single uniform
projector contract.
"""

from __future__ import annotations

import re
from pathlib import Path

from gaia.engine.codegen import render_call_statement, render_module
from gaia.engine.projector.api import (
    GeneratedFile,
    ProjectionResult,
    QueueItem,
    SourceMapRecord,
)
from gaia.engine.projector.host_kind import HostKind

__all__ = ["project_generic"]


_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SAFE_SLUG_RE = re.compile(r"[^a-z0-9_]+")


def project_generic(
    host: Path,
    *,
    kind: HostKind,
    seeds: list[Path],
) -> ProjectionResult:
    """Project arbitrary host files into ``note(...)`` scaffolds."""
    files: list[GeneratedFile] = []
    source_map: list[SourceMapRecord] = []
    queue: list[QueueItem] = []

    if seeds:
        files.append(
            GeneratedFile(
                path="gaia/from_host/__init__.py",
                body='"""Deterministic scaffold projections of host files."""\n\n'
                "__all__: list[str] = []\n",
            )
        )

    used_stems: set[str] = set()
    for index, seed in enumerate(seeds, start=1):
        stem = _safe_stem(host, seed, index, used_stems)
        used_stems.add(stem)
        label = f"host_{stem}"
        host_rel = seed.relative_to(host).as_posix()
        snippet = _read_snippet(seed)
        statement = render_call_statement(
            target_label=label,
            func_name="note",
            positional=[
                f"Scaffold projection of host file `{host_rel}`. "
                "Replace this stub with structured Gaia DSL once the host's "
                "contents are understood."
            ],
            keywords={
                "metadata": {
                    "source_path": host_rel,
                    "projection_mode": "scaffold",
                    "projection_rule": "host.file.note.v1",
                    "preview": snippet,
                }
            },
        )
        body = render_module(
            docstring=(
                f"Deterministic scaffold projection of host file `{host_rel}`.\n\n"
                "Generated by `gaia pkg mount --from <host-file>` / "
                "`gaia build init --embedded`. Scaffold mode emits only "
                "safe, low-risk records (`note(...)`); upgrade through "
                "`.gaia/formalization_queue.jsonl`."
            ),
            engine_imports=("note",),
            statements=[statement],
            all_labels=[label],
        )
        files.append(GeneratedFile(path=f"gaia/from_host/{stem}.py", body=body))

        queue_id = f"FQ{index:04d}"
        source_map.append(
            SourceMapRecord(
                source_id=f"HOST:{host_rel}",
                source_path=host_rel,
                gaia_label=label,
                gaia_record_kind="note",
                generated_file=f"gaia/from_host/{stem}.py",
                projection_rule="host.file.note.v1",
                requires_review=True,
                queue_id=queue_id,
            )
        )
        queue.append(
            QueueItem(
                queue_id=queue_id,
                source_id=f"HOST:{host_rel}",
                source_refs=[host_rel],
                current_gaia_record=label,
                current_action="note",
                candidate_actions=["claim", "observe", "depends_on"],
                reason_review_needed=(
                    "Scaffold mode emitted a note(...) stub; the user/agent must "
                    "decide whether the host file should project to a claim, "
                    "observation, or dependency."
                ),
            )
        )

    return ProjectionResult(host_kind=kind, files=files, source_map=source_map, queue=queue)


def _safe_stem(host: Path, seed: Path, index: int, used: set[str]) -> str:
    rel = seed.relative_to(host)
    raw = "_".join(rel.with_suffix("").parts) if rel.parts else rel.stem
    stem = _SAFE_SLUG_RE.sub("_", raw.lower()).strip("_")
    if not stem or not _IDENT_RE.match(stem):
        stem = "from_host"
    if stem in used:
        stem = f"{stem}_{index}"
    return stem


def _read_snippet(seed: Path) -> str:
    """Return a short utf-8 preview of *seed* for the generated metadata.

    Binary or unreadable files yield an empty preview rather than
    failing the projector — scaffold mode is intentionally tolerant.
    """
    try:
        data = seed.read_bytes()
    except OSError:
        return ""
    text = data.decode("utf-8", errors="replace").replace("\r\n", "\n").strip()
    if len(text) > 400:
        return text[:400] + "\u2026"
    return text
