"""Pydantic v2 schema for the embedded ``gaia/gaia.toml`` manifest.

Where ``pyproject.toml`` is a PEP-621 standard surface that Gaia has
no say over, ``gaia/gaia.toml`` is a Gaia-owned manifest and we treat
it as a real schema: explicit field types, ``schema_version``, and
validation errors that point at the offending key. This replaces the
inline ``isinstance`` checks the original embedded-layout loader did
against a raw ``dict`` read from TOML.

The schema mirrors the on-disk shape one-to-one — ``[package]``,
``[quality]``, ``[projection]`` — and is intentionally permissive
about extra keys (``model_config = ConfigDict(extra="allow")``) so
that downstream tooling can stash projector / queue / registry hints
in the manifest without forcing a new schema_version every time.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Annotated, Any

import tomli_w
from pydantic import BaseModel, ConfigDict, Field, field_validator

try:
    import tomllib
except ImportError:  # pragma: no cover — Python <3.11 fallback
    import tomli as tomllib  # type: ignore[no-redef]


__all__ = [
    "GAIA_MANIFEST_HEADER",
    "GAIA_MANIFEST_SCHEMA_VERSION",
    "GaiaManifest",
    "GaiaManifestError",
    "GaiaPackageBlock",
    "GaiaProjectionBlock",
    "GaiaQualityBlock",
    "load_manifest",
    "render_manifest",
]


GAIA_MANIFEST_HEADER = (
    "# Gaia knowledge-package identity.\n"
    "# This file is the only thing Gaia needs to recognise a host directory\n"
    "# as a knowledge package. The host's own pyproject.toml (if any) stays\n"
    "# a plain Python project — no [tool.gaia] block required.\n\n"
)


GAIA_MANIFEST_SCHEMA_VERSION = 1
"""Current ``gaia.toml`` schema version.

A manifest with ``schema_version`` greater than this constant raises
:class:`GaiaManifestError` rather than silently degrading — the host
was authored against a newer Gaia release than the one trying to
load it, and silently dropping unknown fields would risk semantic
drift in the compiled IR.

A manifest with ``schema_version`` equal to this constant validates
strictly against the schema below. A manifest missing the field
entirely defaults to ``1`` so the first generation of mounts (which
were written before ``schema_version`` existed) keeps loading.
"""


_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")


class GaiaManifestError(ValueError):
    """Raised when ``gaia.toml`` is missing, malformed, or schema-incompatible."""


class GaiaPackageBlock(BaseModel):
    """The ``[package]`` table — Gaia package identity.

    The user-facing package name (``name``) is what shows up in QIDs,
    manifest entries, and registry coordinates. The legacy ``-gaia``
    suffix is allowed but never required; if present, the loader
    strips it the same way ``project_name.removesuffix("-gaia")`` did
    in the historical layout, so a host migrating from legacy keeps
    byte-identical IR.
    """

    model_config = ConfigDict(extra="forbid")

    name: Annotated[str, Field(min_length=1, description="User-facing package name.")]
    version: Annotated[str, Field(min_length=1, description="Semantic version string.")] = "0.0.0"
    namespace: Annotated[str, Field(min_length=1, description="QID namespace.")] = "github"
    description: str | None = Field(default=None, description="Short human-readable summary.")
    uuid: str | None = Field(
        default=None,
        description=(
            "Stable UUID for the package, used by `gaia pkg register`. "
            "Auto-generated by `gaia pkg mount` / `gaia pkg migrate` so registration "
            "works on embedded layouts without an extra step."
        ),
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="PEP-508 requirement strings for Gaia or non-Gaia dependencies.",
    )
    host_kind: str | None = Field(
        default=None,
        description=(
            "Detected host kind. One of 'arm', 'ara', 'python-package', or 'generic'. "
            "Written by `gaia pkg mount` / `gaia build init --embedded` after host "
            "introspection; never required to be set by hand."
        ),
    )

    @field_validator("name")
    @classmethod
    def _name_yields_valid_python_identifier(cls, value: str) -> str:
        normalised = value.removesuffix("-gaia").replace("-", "_")
        if not _IDENT_RE.match(normalised):
            raise ValueError(
                f"package name {value!r} does not normalise to a valid Python identifier "
                f"(got {normalised!r}; identifiers must start with a letter or '_' and "
                "contain only letters, digits, '-' or '_')."
            )
        return value

    @field_validator("host_kind")
    @classmethod
    def _host_kind_in_known_set(cls, value: str | None) -> str | None:
        if value is None:
            return value
        known = {"arm", "ara", "python-package", "generic"}
        if value not in known:
            raise ValueError(f"host_kind {value!r} is not recognised. Use one of: {sorted(known)}.")
        return value


class GaiaQualityBlock(BaseModel):
    """The ``[quality]`` table — package-level publish gates."""

    model_config = ConfigDict(extra="allow")

    allow_holes: bool = Field(
        default=True,
        description=(
            "Whether the package may compile with unsupported leaf claims. "
            "Set to False to force every claim to have a supporting strategy "
            "before `gaia pkg register` accepts the package."
        ),
    )


class GaiaProjectionBlock(BaseModel):
    """The ``[projection]`` table — deterministic projector policy.

    Records the host kind and projector parameters used when the
    embedded package was last regenerated from a host (ARM bundle,
    ARA artifact, etc.). Pure metadata as far as ``load_gaia_package``
    is concerned, but consumed by the projector subcommands and the
    ``.gaia/source_map.json`` audit spine.
    """

    model_config = ConfigDict(extra="allow")

    mode: str = Field(
        default="scaffold",
        description="One of 'scaffold', 'formalized', 'locked' (spec §5).",
    )
    seed_files: list[str] = Field(
        default_factory=list,
        description="Host-relative paths the projector last consumed.",
    )

    @field_validator("mode")
    @classmethod
    def _mode_in_known_set(cls, value: str) -> str:
        known = {"scaffold", "formalized", "locked"}
        if value not in known:
            raise ValueError(f"projection.mode must be one of {sorted(known)}, got {value!r}.")
        return value


class GaiaManifest(BaseModel):
    """The full ``gaia/gaia.toml`` document.

    Strict on the typed blocks (``[package]``, ``[quality]``,
    ``[projection]``) but permissive at the top level so downstream
    tooling can attach its own tables without bumping the schema
    version on every change. Anything outside the three named blocks
    rides in :attr:`extras` for later introspection.
    """

    model_config = ConfigDict(extra="allow")

    schema_version: int = Field(
        default=GAIA_MANIFEST_SCHEMA_VERSION,
        description="Manifest schema version. See GAIA_MANIFEST_SCHEMA_VERSION.",
    )
    package: GaiaPackageBlock
    quality: GaiaQualityBlock = Field(default_factory=GaiaQualityBlock)
    projection: GaiaProjectionBlock = Field(default_factory=GaiaProjectionBlock)

    @field_validator("schema_version")
    @classmethod
    def _schema_version_known(cls, value: int) -> int:
        if value < 1:
            raise ValueError(f"gaia.toml schema_version must be >= 1, got {value}.")
        if value > GAIA_MANIFEST_SCHEMA_VERSION:
            raise ValueError(
                f"gaia.toml schema_version={value} is newer than this gaia-lang knows "
                f"about (supported up to {GAIA_MANIFEST_SCHEMA_VERSION}). Upgrade "
                "gaia-lang and retry."
            )
        return value

    def to_raw_dict(self) -> dict[str, Any]:
        """Return the manifest as a TOML-friendly dict (no None values).

        ``extra="allow"`` keeps unknown top-level keys in
        ``__pydantic_extra__``; ``model_dump`` surfaces them too so
        downstream tools can read them without poking at private
        attrs.
        """
        return self.model_dump(exclude_none=True)


def load_manifest(path: str | Path) -> GaiaManifest:
    """Read ``gaia.toml`` from disk and return a validated :class:`GaiaManifest`.

    All on-disk failure modes (missing file, malformed TOML, schema
    mismatch) bubble up as :class:`GaiaManifestError` so the caller
    has one exception class to catch.
    """
    manifest_path = Path(path)
    if not manifest_path.exists():
        raise GaiaManifestError(f"gaia.toml not found at {manifest_path}.")
    try:
        with open(manifest_path, "rb") as f:
            raw = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise GaiaManifestError(f"gaia.toml at {manifest_path} is not valid TOML: {exc}") from exc
    try:
        return GaiaManifest.model_validate(raw)
    except Exception as exc:  # pydantic ValidationError or anything below
        raise GaiaManifestError(
            f"gaia.toml at {manifest_path} failed schema validation: {exc}"
        ) from exc


def render_manifest(manifest: GaiaManifest, *, header: str | None = GAIA_MANIFEST_HEADER) -> str:
    """Serialise a :class:`GaiaManifest` to its on-disk TOML form.

    Uses ``tomli_w`` (already pulled in via ``tomli-w>=1.2.0`` in the
    project dependencies) so escaping, quoting, and key ordering are
    delegated to a real TOML writer rather than f-string templating.
    The output round-trips through :func:`load_manifest` to the same
    :class:`GaiaManifest` value.

    The optional *header* is prepended verbatim (and unparsed) so the
    generated file carries a short human-readable preamble explaining
    the manifest's purpose. Pass ``header=None`` to skip it.
    """
    payload = manifest.model_dump(exclude_none=True)
    body = tomli_w.dumps(payload)
    if header:
        return f"{header}{body}"
    return body
