"""``gaia sdk`` — generate the SDK reference + cheat sheet.

This is the **first/primary** entry point: authoring the Gaia DSL directly
via the Python SDK is the recommended path. ``gaia sdk`` (no subcommand)
writes a self-contained Markdown reference into ``--out`` (default
``./gaia-sdk/``):

* ``<out>/CHEATSHEET.md`` — a one-page distillation (every verb / term /
  distribution with a copy-pasteable example).
* ``<out>/index.md`` + one page per SDK module — the full per-symbol API
  reference, introspected from the public API surface (no mkdocs / sphinx
  runtime dependency).

The reference is generated by introspecting ``gaia.engine.lang`` and
``gaia.engine.bayes`` (names / signatures / Google-style docstrings),
filtering ``_``-prefixed privates the same way the Pages-site
mkdocstrings config does.
"""

from __future__ import annotations

from pathlib import Path

import typer

from gaia.cli.commands.sdk._cheatsheet import CHEATSHEET_MD
from gaia.cli.commands.sdk._introspect import (
    introspect_sdk,
    module_page_name,
    render_index_markdown,
    render_module_markdown,
)


def sdk_command(
    out: str = typer.Option(
        "./gaia-sdk/",
        "--out",
        help="Directory to write the SDK reference + cheat sheet into (default: ./gaia-sdk/).",
    ),
) -> None:
    """Generate the Gaia SDK reference + cheat sheet (start here).

    Writing the DSL directly via the Python SDK is the primary authoring
    path. This command drops a self-contained Markdown reference plus a
    one-page cheat sheet into ``--out`` so you can read the surface and
    author your package directly.
    """
    out_path = Path(out)
    out_dir = out_path.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Cheat sheet at the top tier of --out.
    cheatsheet_path = out_dir / "CHEATSHEET.md"
    cheatsheet_path.write_text(CHEATSHEET_MD)

    # Full per-module reference, introspected from the public API surface.
    docs = introspect_sdk()
    index_path = out_dir / "index.md"
    index_path.write_text(render_index_markdown(docs))
    for doc in docs:
        page_path = out_dir / module_page_name(doc.module)
        page_path.write_text(render_module_markdown(doc))

    # Stdout contract (exact ordering): cheatsheet location first, then
    # the full SDK docs pointer. Echo paths in the user's ``--out``
    # spelling (e.g. ``./gaia-sdk/CHEATSHEET.md``) when relative.
    prefix = out.rstrip("/")
    if out_path.is_absolute():
        cheatsheet_display = str(cheatsheet_path)
        docs_display = str(out_dir)
    else:
        cheatsheet_display = f"{prefix}/CHEATSHEET.md"
        docs_display = f"{prefix}/"
    typer.echo(f"✓ Cheatsheet written → {cheatsheet_display}")
    typer.echo(
        f"  Full SDK reference → {docs_display}  (start here, then author your DSL directly)"
    )


__all__ = ["sdk_command"]
